appIndex: "apps/usermanagement/sdsd"
proxyPath: "a_path"
version: "2.0.1"
icon: "{icon-square}mif-user"
iconSmall: "{icon}mif-user"
width: "800"
minWidth: "470"
height: "500"
minHeight: "450"
active: true
multipleInstances: false
restrictAccess: true
resizable: true
draggable: true
closable: true
minimizable: true
maximizable: true
system: false
showTitle: false
stripPrefix: false
sensitiveHeaders: "xmm"
translationsGroup: "angularmaterial"
