--- 
- 
  active: true
  addedOn: 2121545432165
  appIndex: "https://www.meteo.gr/cf.cfm?city_id=1"
  checksum: 866f232231447521369b01db7006d2c26e5c6b2e796342d344501287e9e97a52
  closable: true
  draggable: true
  groupName: ""
  height: 500
  icon: "https://www.eurodyn.com/wp-content/uploads/2018/11/logo_efdms.png"
  iconSmall: "{icon}mif-user"
  id: 088c8e4e-9eae-4885-a15e-01fd5cd6e122
  lastDeployedOn: 2121545432162
  lexicon: ~
  maximizable: true
  minHeight: 450
  minWidth: 470
  minimizable: true
  multipleInstances: false
  proxyPath: /applications
  resizable: true
  restrictAccess: true
  sensitiveHeaders: "Cookie, Set-Cookie."
  showTitle: false
  stripPrefix: false
  system: false
  translationsGroup: usermanagement2
  version: "2.0.1"
  width: 800
- 
  active: true
  addedOn: 2121545432165
  appIndex: "https://material.angular.io/"
  checksum: 866f232231447521369b01db7006d2c26e5c6b2e796342d344501287e9e97a51
  closable: true
  draggable: true
  groupName: group1
  height: 500
  icon: "https://cdn.dribbble.com/assets/dribbble-vector-ball-95ca193529993e9b3904f7adb541680aba196642f557cfaf3cdbb0a48a284be4.svg"
  iconSmall: "{icon}mif-user"
  id: 088c8e4e-9eae-4885-a15e-01fd5cd6e221
  lastDeployedOn: 2121545432161
  lexicon: ~
  maximizable: true
  minHeight: 450
  minWidth: 470
  minimizable: true
  multipleInstances: false
  proxyPath: a_proxy_path
  resizable: true
  restrictAccess: true
  sensitiveHeaders: "Cookie, Set-Cookie."
  showTitle: false
  stripPrefix: false
  system: false
  translationsGroup: usermanagement1
  version: "2.0.1"
  width: 800
- 
  active: true
  addedOn: 2121545432163
  appIndex: "https://www.webex.com"
  checksum: 866f232231447521369b01db7006d2c26e5c6b2e796342d344501287e9e97a53
  closable: true
  draggable: true
  groupName: ""
  height: 500
  icon: "https://www.eurodyn.com/wp-content/uploads/2018/11/logo_ed.png"
  iconSmall: "{icon}mif-user"
  id: 088c8e4e-9eae-4885-a15e-01fd5cd6e223
  lastDeployedOn: 2121545432163
  lexicon: ~
  maximizable: true
  minHeight: 450
  minWidth: 470
  minimizable: true
  multipleInstances: false
  proxyPath: a_proxy_path
  resizable: true
  restrictAccess: true
  sensitiveHeaders: "Cookie, Set-Cookie."
  showTitle: false
  stripPrefix: false
  system: false
  translationsGroup: usermanagement3
  version: "2.0.1"
  width: 800
- 
  active: true
  addedOn: 2121545432163
  appIndex: "https://www.eurodyn.com/"
  checksum: 866f232231447521369b01db7006d2c26e5c6b2e796342d344501287e9e97a54
  closable: true
  draggable: true
  groupName: group1
  height: 500
  icon: "https://www.eurodyn.com/wp-content/uploads/2018/10/european_dynamics_fav.png"
  iconSmall: "https://www.eurodyn.com/wp-content/uploads/2018/10/european_dynamics_fav.png"
  id: 088c8e4e-9eae-4885-a15e-01fd5cd6e224
  lastDeployedOn: 2121545432164
  lexicon: ~
  maximizable: true
  minHeight: 450
  minWidth: 470
  minimizable: true
  multipleInstances: false
  proxyPath: a_proxy_path
  resizable: true
  restrictAccess: true
  sensitiveHeaders: "Cookie, Set-Cookie."
  showTitle: false
  stripPrefix: false
  system: false
  translationsGroup: usermanagement4
  version: "2.0.1"
  width: 800
- 
  active: true
  addedOn: 2121545432165
  appIndex: "https://angular.io/"
  checksum: 866f232231447521369b01db7006d2c26e5c6b2e796342d344501287e9e97a59
  closable: true
  draggable: true
  groupName: group2
  height: 500
  icon: "{icon-square}mif-user"
  iconSmall: "{icon}mif-user"
  id: 088c8e4e-9eae-4885-a15e-01fd5cd6e227
  lastDeployedOn: 2121545432165
  lexicon: ~
  maximizable: true
  minHeight: 850
  minWidth: 470
  minimizable: true
  multipleInstances: false
  proxyPath: a_proxy_path
  resizable: true
  restrictAccess: true
  sensitiveHeaders: "Cookie, Set-Cookie."
  showTitle: false
  stripPrefix: false
  system: false
  translationsGroup: usermanagement5
  version: "2.0.1"
  width: 500
