appIndex: "apps/usermanagement/sdsd"
proxyPath: "a_path"
version: "2.0.1"
icon: "{icon-square}mif-user"
iconSmall: "{icon}mif-user"
width: "800"
minWidth: "470"
height: "500"
minHeight: "450"
active: true
multipleInstances: false
restrictAccess: true
resizable: true
draggable: true
closable: true
minimizable: true
maximizable: true
system: false
showTitle: false
stripPrefix: false
sensitiveHeaders: "xmm"
applicationName: "angularmaterial ddsadsaddsssd"
lexicon:
- languageLocale: "en"
  key: "title"
  value: "angularmaterialsssssssss en"
- languageLocale: "en"
  key: "description"
  value: "angularmaterialDescription en"
- languageLocale: "el"
  key: "title"
  value: "angularmaterial EL"
- languageLocale: "el"
  key: "description"
  value: "angularmaterialDescription EL"
- languageLocale: "fr"
  key: "title"
  value: "angularmaterial FR"
- languageLocale: "fr"
  key: "description"
  value: "angularmaterialDescription FR"
