---
- id: "088c8e4e-9eae-4885-a15e-01fd5cd6e122"
  version: "2.0.1"
  proxyPath: "/applications"
  appIndex: "https://www.meteo.gr/cf.cfm?city_id=1"
  multipleInstances: false
  restrictAccess: true
  icon: "https://www.eurodyn.com/wp-content/uploads/2018/11/logo_efdms.png"
  iconSmall: "{icon}mif-user"
  width: 800
  minWidth: 470
  height: 500
  minHeight: 450
  resizable: true
  minimizable: true
  maximizable: true
  closable: true
  draggable: true
  translationsGroup: "usermanagement2"
  lexicon: null
  active: true
  addedOn: 2121545432165
  lastDeployedOn: 2121545432162
  system: false
  showTitle: false
  checksum: "866f232231447521369b01db7006d2c26e5c6b2e796342d344501287e9e97a52"
  groupName: ""
  stripPrefix: false
  sensitiveHeaders: "Cookie, Set-Cookie."
